openapi: 3.0.3
info:
  title: tRPC OpenAPI
  description: null
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  '/module/{moduleCode}':
    get:
      operationId: module
      summary: Get a single module
      description: null
      tags:
        - Module
      security: null
      parameters:
        - name: moduleCode
          in: path
          required: true
          schema:
            type: string
            pattern: ^[A-Z]{2,4}[0-9]{4}[A-Z]{0,5}[0-9]{0,2}$
          description: null
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    enum:
                      - true
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        format: uuid
                      moduleCode:
                        type: string
                        pattern: ^[A-Z]{2,4}[0-9]{4}[A-Z]{0,5}[0-9]{0,2}$
                      title:
                        type: string
                      prerequisite:
                        type: string
                      corequisite:
                        type: string
                      preclusion:
                        type: string
                      fulfillRequirements:
                        type: array
                        items:
                          type: string
                          pattern: ^[A-Z]{2,4}[0-9]{4}[A-Z]{0,5}[0-9]{0,2}$
                      prereqTree:
                        anyOf:
                          - type: string
                          - type: object
                            properties:
                              and:
                                type: array
                                items:
                                  type: object
                                  properties: {}
                                  additionalProperties: false
                              or:
                                type: array
                                items:
                                  type: object
                                  properties: {}
                                  additionalProperties: false
                            additionalProperties: false
                    required:
                      - id
                      - moduleCode
                      - title
                      - prerequisite
                      - corequisite
                      - preclusion
                      - fulfillRequirements
                      - prereqTree
                    additionalProperties: false
                required:
                  - ok
                  - data
                additionalProperties: false
        default:
          $ref: '#/components/responses/error'
  '/module-condensed/{moduleCode}':
    get:
      operationId: module-condensed
      summary: Get a single module condensed
      description: null
      tags:
        - Module
      security: null
      parameters:
        - name: moduleCode
          in: path
          required: true
          schema:
            type: string
            pattern: ^[A-Z]{2,4}[0-9]{4}[A-Z]{0,5}[0-9]{0,2}$
          description: null
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    enum:
                      - true
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        format: uuid
                      moduleCode:
                        type: string
                        pattern: ^[A-Z]{2,4}[0-9]{4}[A-Z]{0,5}[0-9]{0,2}$
                      title:
                        type: string
                    required:
                      - id
                      - moduleCode
                      - title
                    additionalProperties: false
                required:
                  - ok
                  - data
                additionalProperties: false
        default:
          $ref: '#/components/responses/error'
  '/module-full/{moduleCode}':
    get:
      operationId: module-full
      summary: Get a single module full
      description: null
      tags:
        - Module
      security: null
      parameters:
        - name: moduleCode
          in: path
          required: true
          schema:
            type: string
            pattern: ^[A-Z]{2,4}[0-9]{4}[A-Z]{0,5}[0-9]{0,2}$
          description: null
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    enum:
                      - true
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        format: uuid
                      acadYear:
                        type: string
                      moduleCode:
                        type: string
                        pattern: ^[A-Z]{2,4}[0-9]{4}[A-Z]{0,5}[0-9]{0,2}$
                      title:
                        type: string
                      description:
                        type: string
                      moduleCredit:
                        type: string
                      department:
                        type: string
                      faculty:
                        type: string
                      aliases:
                        type: array
                        items:
                          type: string
                          pattern: ^[A-Z]{2,4}[0-9]{4}[A-Z]{0,5}[0-9]{0,2}$
                      attributes:
                        type: object
                        properties: {}
                        additionalProperties: false
                      prerequisite:
                        type: string
                      corequisite:
                        type: string
                      preclusion:
                        type: string
                      fulfillRequirements:
                        $ref: '#/properties/data/properties/aliases'
                      semesterData:
                        type: array
                        items:
                          type: object
                          properties: {}
                          additionalProperties: false
                      prereqTree:
                        anyOf:
                          - type: string
                          - type: object
                            properties:
                              and:
                                type: array
                                items:
                                  type: object
                                  properties: {}
                                  additionalProperties: false
                              or:
                                type: array
                                items:
                                  type: object
                                  properties: {}
                                  additionalProperties: false
                            additionalProperties: false
                      workload:
                        anyOf:
                          - type: string
                          - type: array
                            items:
                              type: number
                    required:
                      - id
                      - acadYear
                      - moduleCode
                      - title
                      - description
                      - moduleCredit
                      - department
                      - faculty
                      - aliases
                      - attributes
                      - prerequisite
                      - corequisite
                      - preclusion
                      - fulfillRequirements
                      - semesterData
                      - prereqTree
                      - workload
                    additionalProperties: false
                required:
                  - ok
                  - data
                additionalProperties: false
        default:
          $ref: '#/components/responses/error'
  '/search/modules/{search}':
    get:
      operationId: search/modules
      summary: Get many modules condensed
      description: null
      tags:
        - Module
      security: null
      parameters:
        - name: search
          in: path
          required: true
          schema:
            type: string
          description: null
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    enum:
                      - true
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                        moduleCode:
                          type: string
                          pattern: ^[A-Z]{2,4}[0-9]{4}[A-Z]{0,5}[0-9]{0,2}$
                        title:
                          type: string
                        prerequisite:
                          type: string
                        corequisite:
                          type: string
                        preclusion:
                          type: string
                        fulfillRequirements:
                          type: array
                          items:
                            type: string
                            pattern: ^[A-Z]{2,4}[0-9]{4}[A-Z]{0,5}[0-9]{0,2}$
                        prereqTree:
                          anyOf:
                            - type: string
                            - type: object
                              properties:
                                and:
                                  type: array
                                  items:
                                    type: object
                                    properties: {}
                                    additionalProperties: false
                                or:
                                  type: array
                                  items:
                                    type: object
                                    properties: {}
                                    additionalProperties: false
                              additionalProperties: false
                      required:
                        - id
                        - moduleCode
                        - title
                        - prerequisite
                        - corequisite
                        - preclusion
                        - fulfillRequirements
                        - prereqTree
                      additionalProperties: false
                required:
                  - ok
                  - data
                additionalProperties: false
        default:
          $ref: '#/components/responses/error'
  '/search/modules-condensed/{search}':
    get:
      operationId: search/modules-condensed
      summary: Get many modules condensed
      description: null
      tags:
        - Module
      security: null
      parameters:
        - name: search
          in: path
          required: true
          schema:
            type: string
          description: null
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    enum:
                      - true
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                        moduleCode:
                          type: string
                          pattern: ^[A-Z]{2,4}[0-9]{4}[A-Z]{0,5}[0-9]{0,2}$
                        title:
                          type: string
                      required:
                        - id
                        - moduleCode
                        - title
                      additionalProperties: false
                required:
                  - ok
                  - data
                additionalProperties: false
        default:
          $ref: '#/components/responses/error'
components:
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
  responses:
    error:
      description: Error response
      content:
        application/json:
          schema:
            type: object
            properties:
              ok:
                type: boolean
                enum:
                  - false
              error:
                type: object
                properties:
                  message:
                    type: string
                  code:
                    type: string
                  issues:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
                      required:
                        - message
                      additionalProperties: false
                required:
                  - message
                  - code
                additionalProperties: false
            required:
              - ok
              - error
            additionalProperties: false
tags: null
externalDocs: null
