module.exports = {
  sync: 'node scripts/sync-scripts.js',
  'build:web': 'next build apps/web',
  'dev:web': 'next dev apps/web',
  'build:server': 'node apps/server/dev.js --build',
  'dev:server': 'node apps/server/dev.js --watch',
  'build:docs': 'cd apps/docs && yarn bundle && yarn build',
  'dev:docs': 'cd apps/docs && yarn bundle && yarn dev',
  build: 'node .github/scripts/build-all.js',
  dev: 'node scripts/serve.js',
  up: 'cd docker && docker compose --profile db up --detach',
  down: 'cd docker && docker compose --profile all down',
  'docker:cy-reporter': 'node docker/cy-reporter/build.js',
  'docker:server': 'node docker/server/build.js',
  cy: 'node libs/cy-reporter/entry.js',
  'cy:dev': 'node libs/cy-reporter/dev.js --watch',
  'cy:build': 'node libs/cy-reporter/dev.js --build',
  test: 'bash scripts/run-tests/run.sh',
  'test:dev': 'yarn test:build && yarn test',
  'test:scan': 'ts-node scripts/run-tests/scan.ts',
  'test:build': 'yarn test:scan && node scripts/run-tests/build.js',
  e2e: 'node scripts/cypress/open.js',
  mg: 'bash scripts/migration/generate.sh',
  mr: 'bash scripts/migration/run.sh',
  tc: 'bash scripts/migration/test-connect.sh',
  version: 'auto-changelog -p && git add --all',
  i: 'bash scripts/yarn.sh inverse || exit 0',
  prepare: 'bash scripts/yarn.sh setup || exit 0',
}
