export { ModuleCondensedRepository } from './ModuleCondensed'
export { ModuleRepository } from './Module'
export { DegreeRepository } from './Degree'
export { UserRepository } from './User'
export { GraphRepository } from './Graph'
