export { ModuleRepository } from './Module'
export { ModuleCondensedRepository } from './ModuleCondensed'
export { DegreeRepository } from './Degree'
export { UserRepository } from './User'
export { DAGRepository } from './DAG'
