#!/usr/bin/env bash

if [[ $1 == 'Dockerfile.server' ]]; then
  docker build -f $1 -t modtree/server ../
fi

if [[ $1 == 'Dockerfile.postgres' ]]; then
  docker build -f $1 -t modtree/postgres ../
fi

if [[ $1 == 'Dockerfile.node' ]]; then
  docker build -f $1 -t modtree/node ../
fi

if [[ $1 == 'Dockerfile.yarn' ]]; then
  docker build -f $1 -t modtree/yarn ../
fi
