FROM modtree/node:0.5.0

# load yarn post-setup script
WORKDIR /app/scripts
COPY scripts/yarn.sh .

# load packages-related files
WORKDIR /app
COPY package.json .
COPY yarn.lock .

# install dependencies
RUN yarn install --frozen-lockfile
