FROM node:16-alpine

# install python
ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python

# Install yarn and other dependencies via apk
RUN apk add bash g++ make git

# clear cache
RUN rm -rf /var/cache/apk/*
