FROM modtree/node:0.5.0

# load yarn post-setup script
WORKDIR /app/scripts
COPY scripts/yarn.sh .

# load packages-related files
WORKDIR /app

COPY . .

# do all this in one layer so it doesn't cache too much
RUN yarn install --frozen-lockfile \
&& yarn build:server \
&& rm -rf node_modules

CMD ["node", "dist/apps/server/bundle.js"]
