export { ModuleRepository } from './module'
export { ModuleCondensedRepository } from './module-condensed'
export { DegreeRepository } from './degree'
export { UserRepository } from './user'
export { GraphRepository } from './graph'
