name: ci (no nx cache)

on:
  push:
    branches:
      - main

env:
  PREFIX: TEST_POSTGRES_USERNAME=runner TEST_POSTGRES_PASSWORD=runner

jobs:
  ci: # don't change this name, else will also need to change branch rules
    if: always()
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        project:
          - repo-api
          - repo-base
          - repo-degree
          - repo-graph
          - repo-module
          - repo-user
          - utils
          - docs
          - server
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn --frozen-lockfile

      - name: Start PostgreSQL
        run: ./.github/scripts/postgres.sh

      - name: 📦 Run tests for ${{ matrix.project }}
        run: ${{ env.PREFIX }} yarn nx test ${{ matrix.project }} --coverage --skip-nx-cache

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

  build: # don't change this name, else will also need to change branch rules
    if: always()
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1.6.0
        continue-on-error: true
      - run: yarn install --frozen-lockfile --silent
        continue-on-error: true

      - name: 📦 Build entire workspace
        run: yarn build
