on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  push:
    branches:
      - ci-test
      - dev
      - k
      - w

env:
  MYSQL_DATABASE: test_db
  DB_USER: root
  DB_PASSWORD: root
  RESTORE: .test.sql

jobs:
  database-unit-tests:
    runs-on: ubuntu-20.04
      
    steps:
      - name: 🔥 Initialize MySQL
        # run: sudo /etc/init.d/mysql start
        run: sudo systemctl start mysql.service
      
      - name: 🚀 Boost user
        run: |
          mysql -e "ALTER USER '${{ env.DB_USER }}'@'localhost' \
          IDENTIFIED WITH mysql_native_password BY 'root';" \
          -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

      - name: 🍺 Check out repository code
        uses: actions/checkout@v3

      # - name: 🧶 Install yarn
      #   run: yarn install --frozen-lockfile
      #
      - name: NPM or Yarn install with caching
        uses: bahmutov/npm-install@v1.6.0


      - name: 📦 run tests
        working-directory: ./packages/database
        run: |
          MYSQL_RESTORE_SOURCE=$RESTORE \
          MYSQL_USERNAME=$DB_USER \
          MYSQL_PASSWORD=$DB_PASSWORD \
          MYSQL_ACTIVE_DATABASE=$MYSQL_DATABASE \
          yarn test:ci
