name: Deploy Backend Functions

on:
  pull_request:
    types: [opened, reopened]

jobs:
  deploy_to_firebase:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: cd database/functions && yarn deploy
