name: docs

on:
  push:
    branches:
      - docs
      - ci

jobs:
  deploy_docs:
    runs-on: ubuntu-20.04
    steps:
      - name: 🍺 Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: modtree/modtree
          path: other_repo
          token: ${{secrets.PUSH_TOKEN}}

      - name: 🚀 Send it.
        run: |
          cd other_repo
          git config --local user.name "docs-deploy[bot]"
          git config --local user.email "docs-deploy@modtree.nus"
          git checkout docs
          git checkout -b docs-deploy
          git push https://$USERNAME:$REPO_KEY@github.com/nguyenvukhang/modtree-deploy.git docs-deploy
        env:
          USERNAME: docs-deploy[bot]
          REPO_KEY: ${{ secrets.PUSH_TOKEN }}
