name: auto deploy

on:
  push:
    branches:
      - docs
      - dev
      - ci

jobs:
  deploy_frontends:
    runs-on: ubuntu-20.04
    steps:
      - name: 🍺 Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: modtree/modtree
          path: other_repo
          token: ${{secrets.PUSH_TOKEN}}

      - name: 🚀 Send it.
        run: |
          cd other_repo
          git config --local user.name "$USERNAME[bot]"
          git config --local user.email "$USERNAME@modtree.nus"
          git checkout -b continuous-deployment
          git push --force https://$USERNAME:$REPO_KEY@github.com/nguyenvukhang/modtree-docs.git
        env:
          USERNAME: auto-deploy[bot]
          REPO_KEY: ${{ secrets.PUSH_TOKEN }}
