name: postgres

on:
  push:
    branches:
      - ci

jobs:
  database_tests:
    runs-on: ubuntu-20.04
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: 🔥 Initialize PostgreSQL
        run: |
          sudo systemctl start postgresql.service
          echo "CREATE USER runner PASSWORD 'runner';" > /tmp/create_user.sql
          echo "ALTER ROLE runner WITH CREATEDB;" >> /tmp/create_user.sql
          echo "ALTER ROLE runner WITH SUPERUSER;" >> /tmp/create_user.sql
          sudo su postgres -c "psql --file=/tmp/create_user.sql"
          createdb base

      - name: 🍺 Check out repository code
        uses: actions/checkout@v3

      - name: 🧶 Install yarn
        run: yarn install --frozen-lockfile
      
      - name: 📦 Run tests
        working-directory: ./packages/database
        run: |
          yarn build
          TEST_DATABASE_TYPE=POSTGRES \
          TEST_POSTGRES_USERNAME=runner \
          TEST_POSTGRES_PASSWORD=runner \
          TEST_POSTGRES_HOST=localhost \
          TEST_POSTGRES_ACTIVE_DATABASE=base \
          TEST_POSTGRES_RESTORE_SOURCE=postgres-modules-only.sql \
          TEST_POSTGRES_SYNC="true" \
          yarn test:k
